# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PEF.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette, QLinearGradient, QColor
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QVBoxLayout, QWidget, QStackedWidget
from PyQt5.QtCore import QTimer



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.image = 120
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.stacked_widget = QStackedWidget()

        self.variavel = 12

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.resultswidget = QtWidgets.QWidget(MainWindow)
        self.resultswidget.setObjectName("resulswidget")

        self.stacked_widget.addWidget(self.centralwidget)
        self.stacked_widget.addWidget(self.resultswidget)


        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 801, 581))
        self.widget.setStyleSheet("background-color: rgba(255, 178, 102, 255);")
        self.widget.setObjectName("widget")

        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(630, 480, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.submit_button.clicked.connect(self.show_results_window)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 80, 171, 71))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.Forca_box = QtWidgets.QLineEdit(self.centralwidget)
        self.Forca_box.setGeometry(QtCore.QRect(620, 420, 131, 20))
        self.Forca_box.setObjectName("Forca_box")

        self.label_forca = QtWidgets.QLabel(self.centralwidget)
        self.label_forca.setGeometry(QtCore.QRect(620, 370, 150, 20))
        self.label_forca.setStyleSheet("color : white")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_forca.setFont(font)
        self.label_forca.setObjectName("label_forca")

        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(120, 10, 600, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")

        self.label_forca2 = QtWidgets.QLabel(self.centralwidget)
        self.label_forca2.setGeometry(QtCore.QRect(590, 390, 185, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_forca2.setFont(font)
        self.label_forca2.setStyleSheet("color : white")
        self.label_forca2.setObjectName("label_forca2")

        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(240, 490, 91, 31))
        self.next_button.setObjectName("next_button")
        self.next_button.clicked.connect(self.incrementar)
        self.next_button.clicked.connect(self.show_ex)

        self.previous_button = QtWidgets.QPushButton(self.centralwidget)
        self.previous_button.setGeometry(QtCore.QRect(90, 490, 91, 31))
        self.previous_button.setObjectName("previous_button")
        self.previous_button.clicked.connect(self.decrementar)
        self.previous_button.clicked.connect(self.show_ex)

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 170, 331, 301))
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.setPixmap(QtGui.QPixmap("ex1.jpg"))

        self.label_warning = QtWidgets.QLabel(self.centralwidget)
        self.label_warning.setGeometry(QtCore.QRect(600, 320, 200, 20))
        self.label_warning.setStyleSheet("color : red")
        self.label_warning.setText("")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_warning.setFont(font)
        self.label_warning.setObjectName("label_warning")
        self.ocultar()



        ## Results widget

        self.widget_cor_results = QtWidgets.QWidget(self.resultswidget)
        self.widget_cor_results.setGeometry(QtCore.QRect(-1, -1, 801, 581))
        self.widget_cor_results.setStyleSheet("background-color: rgba(255, 178, 102, 255);")
        self.widget_cor_results.setObjectName("widget_cor_results")

        self.label_N = QtWidgets.QLabel(self.resultswidget)
        self.label_N.setGeometry(QtCore.QRect(125, 40, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_N.setFont(font)
        self.label_N.setObjectName("label_N")

        self.label_N_fto = QtWidgets.QLabel(self.resultswidget)
        self.label_N_fto.setGeometry(QtCore.QRect(80, 80, 240, 190))
        self.label_N_fto.setText("")
        self.label_N_fto.setScaledContents(True)
        self.label_N_fto.setPixmap(QtGui.QPixmap("grafico_1.png"))
        self.label_N_fto.setObjectName("label_N_fto")

        self.label_V = QtWidgets.QLabel(self.resultswidget)
        self.label_V.setGeometry(QtCore.QRect(510, 10, 180, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_V.setFont(font)
        self.label_V.setObjectName("label_V")

        self.label_V_fto = QtWidgets.QLabel(self.resultswidget)
        self.label_V_fto.setGeometry(QtCore.QRect(480, 80, 240, 190))
        self.label_V_fto.setText("")
        self.label_V_fto.setScaledContents(True)
        self.label_V_fto.setPixmap(QtGui.QPixmap("grafico_2.png"))
        self.label_V_fto.setObjectName("label_V_fto")

        self.label_M = QtWidgets.QLabel(self.resultswidget)
        self.label_M.setGeometry(QtCore.QRect(120, 290, 160, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_M.setFont(font)
        self.label_M.setObjectName("label_M")

        self.label_M_fto = QtWidgets.QLabel(self.resultswidget)
        self.label_M_fto.setGeometry(QtCore.QRect(80, 350, 240, 190))
        self.label_M_fto.setText("")
        self.label_M_fto.setScaledContents(True)
        self.label_M_fto.setPixmap(QtGui.QPixmap("grafico_3.png"))
        self.label_M_fto.setObjectName("label_M_fto")

        self.back_button = QtWidgets.QPushButton(self.resultswidget)
        self.back_button.setGeometry(QtCore.QRect(0, 0, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back_button.setFont(font)
        self.back_button.setObjectName("back_button")
        self.back_button.clicked.connect(self.show_central_window)

        self.label_reacao1 = QtWidgets.QLabel(self.centralwidget)
        self.label_reacao1.setGeometry(QtCore.QRect(450, 340, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_reacao1.setFont(font)
        self.label_reacao1.setObjectName("label_reacao1")


        self.label_reacao2 = QtWidgets.QLabel(self.centralwidget)
        self.label_reacao2.setGeometry(QtCore.QRect(460, 430, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_reacao2.setFont(font)
        self.label_reacao2.setObjectName("label_reacao2")

        self.label_reacao1 = QtWidgets.QLabel(self.resultswidget)
        self.label_reacao1.setGeometry(QtCore.QRect(450, 340, 230, 45))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_reacao1.setFont(font)
        self.label_reacao1.setObjectName("label_reacao1")

        self.label_reacao2 = QtWidgets.QLabel(self.resultswidget)
        self.label_reacao2.setGeometry(QtCore.QRect(450, 430, 230, 45))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_reacao2.setFont(font)
        self.label_reacao2.setObjectName("label_reacao2")




        

        MainWindow.setCentralWidget(self.stacked_widget)


        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


       

        




        




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.submit_button.setText(_translate("MainWindow", "Submeter"))
        self.back_button.setText(_translate("MainWindow", "voltar"))
        self.label.setText(_translate("MainWindow", "Estrutura:"))
        self.label_forca.setText(_translate("MainWindow", "Modulo da força/"))
        self.label_forca2.setText(_translate("MainWindow", "concentração da força(N):"))
        self.label_titulo.setText(_translate("MainWindow", "Cálculo reações de apoio e forças solicitantes:"))
        self.next_button.setText(_translate("MainWindow", "próxima"))
        self.previous_button.setText(_translate("MainWindow", "anterior"))
        self.label_N.setText(_translate("MainWindow", "Força normal :"))
        self.label_V.setText(_translate("MainWindow", "Força cortante:"))
        self.label_M.setText(_translate("MainWindow", "Momento fletor:"))
        self.label_warning.setText(_translate("MainWindow", "Por favor, insira o modulo:"))
        self.label_reacao1.setText(_translate("MainWindow", "Reação de apoio 1 = " + str(self.variavel) + "N"))
        self.label_reacao2.setText(_translate("MainWindow", "Reação de apoio 2 = " + str(self.variavel)) + "N")

    def incrementar(self):
        self.image = self.image+1

    def decrementar(self):
        self.image = self.image-1    

    def show_ex(self):
        if(self.image%12 == 0):
            self.label_2.setPixmap(QtGui.QPixmap("ex1.jpg"))   
        if(self.image%12 == 1):
            self.label_2.setPixmap(QtGui.QPixmap("ex2.jpg"))
        if(self.image%12 == 2):
            self.label_2.setPixmap(QtGui.QPixmap("ex3.jpg"))
        if(self.image%12 == 3):
            self.label_2.setPixmap(QtGui.QPixmap("ex4.jpg"))   
        if(self.image%12 == 4):
            self.label_2.setPixmap(QtGui.QPixmap("ex5.jpg"))
        if(self.image%12 == 5):
            self.label_2.setPixmap(QtGui.QPixmap("ex6.jpg"))   
        if(self.image%12 == 6):
            self.label_2.setPixmap(QtGui.QPixmap("ex7.jpg"))   
        if(self.image%12 == 7):
            self.label_2.setPixmap(QtGui.QPixmap("ex8.jpg"))
        if(self.image%12 == 8):
            self.label_2.setPixmap(QtGui.QPixmap("ex9.jpg"))  
        if(self.image%12 == 9):
            self.label_2.setPixmap(QtGui.QPixmap("ex10.jpg"))   
        if(self.image%12 == 10):
            self.label_2.setPixmap(QtGui.QPixmap("ex11.jpg"))
        if(self.image%12 == 11):
            self.label_2.setPixmap(QtGui.QPixmap("ex12.jpg")) 


    def show_central_window(self):
        self.stacked_widget.setCurrentIndex(0)
    def show_results_window(self):
        tempo_exibicao = 3000
        if (self.Forca_box.text() != ""):
            self.stacked_widget.setCurrentIndex(1)
        else:
            self.label_warning.show()
            self.timer = QtCore.QTimer()
            self.timer.singleShot(tempo_exibicao,self.ocultar)   

        


    def ocultar(self):
        self.label_warning.hide()



          
                    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    MainWindow = QtWidgets.QMainWindow()
    SencodWindow = QtWidgets.QMainWindow()
    main = Ui_MainWindow()
    main.setupUi(MainWindow)


    MainWindow.show()
    sys.exit(app.exec_())
